import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "uebl wolves",
  description: "Generated by the wolves team.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
