import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar"; 
import { CartProvider } from "./context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "uebl wolves",
  description: "Generated by the wolves team.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ cursor: 'url("/images/main-logo1.png"), auto' }}>
        <CartProvider> 
          <Navbar />
          <main>
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
